states = {'AHMEDNAGAR': 0,
  'AKOLA': 0,
  'AMRAVATI': 0,
  'AURANGABAD': 0,
  'BEED': 0,
  'BHANDARA': 0,
  'BULDHANA': 0,
  'CHANDRAPUR': 0,
  'DHULE': 0,
  'GADCHIROLI': 0,
  'GONDIA': 0,
  'HINGOLI': 0,
  'JALGAON': 0,
  'JALNA': 0,
  'KOLHAPUR': 0,
  'LATUR': 0,
  'NAGPUR': 0,
  'NANDED': 0,
  'NANDURBAR': 0,
  'NASHIK': 0,
  'OSMANABAD': 0,
  'PALGHAR': 0,
  'PARBHANI': 0,
  'PUNE': 0,
  'RAIGAD': 0,
  'RATNAGIRI': 0,
  'SANGLI': 0,
  'SATARA': 0,
  'SINDHUDURG': 0,
  'SOLAPUR': 0,
  'THANE': 0,
  'WARDHA': 0,
  'WASHIM': 0,
  'YAVATMAL': 0}

seasons = {'Kharif':0, 'Rabi':0, 'Summer':0, 'Whole Year':0}

crops = {'Arhar/Tur':0, 'Bajra':0, 'Castor seed':0, 'Cotton(lint)':0, 'Gram':0,
       'Groundnut':0, 'Jowar':0, 'Linseed':0, 'Maize':0, 'Moong(Green Gram)':0,
       'Niger seed':0, 'Other  Rabi pulses':0, 'Other Cereals & Millets':0,
       'Other Kharif pulses':0, 'Ragi':0, 'Rapeseed &Mustard':0, 'Rice':0, 'Safflower':0,
       'Sesamum':0, 'Soyabean':0, 'Sugarcane':0, 'Sunflower':0, 'Tobacco':0, 'Urad':0,
       'Wheat':0, 'other oilseeds':0}

soli_types = {'chalky':0, 'clay':0, 'loamy':0,
       'peaty':0, 'sandy':0, 'silt':0, 'silty':0}