# Generated by Django 4.0.3 on 2022-04-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='staus',
            new_name='status',
        ),
    ]
