# Generated by Django 4.0.6 on 2022-09-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropprediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=100)),
                ('districtname', models.CharField(choices=[('AHMEDNAGAR', 'AHMEDNAGAR'), ('AKOLA', 'AKOLA'), ('AMRAVATI', 'AMRAVATI'), ('AURANGABAD', 'AURANGABAD'), ('BEED', 'BEED'), ('BHANDARA', 'BHANDARA'), ('BULDHANA', 'BULDHANA'), ('CHANDRAPUR', 'CHANDRAPUR'), ('DHULE', 'DHULE'), ('GADCHIROLI', 'GADCHIROLI'), ('GONDIA', 'GONDIA'), ('HINGOLI', 'HINGOLI'), ('JALGAON', 'JALGAON'), ('JALNA', 'JALNA'), ('KOLHAPUR', 'KOLHAPUR'), ('LATUR', 'LATUR'), ('NAGPUR', 'NAGPUR'), ('NANDED', 'NANDED'), ('NANDURBAR', 'NANDURBAR'), ('NASHIK', 'NASHIK'), ('PARBHANI', 'PARBHANI'), ('PUNE', 'PUNE'), ('RAIGAD', 'RAIGAD'), ('RATNAGIRI', 'RATNAGIRI'), ('SANGLI', 'SANGLI'), ('SATARA', 'SATARA'), ('SINDHUDURG', 'SINDHUDURG'), ('SOLAPUR', 'SOLAPUR'), ('THANE', 'THANE'), ('WASHIM', 'WASHIM'), ('YAVATMAL', 'YAVATMAL')], max_length=15)),
                ('cropyear', models.IntegerField()),
                ('season', models.CharField(choices=[('Autumn', 'Autumn'), ('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Summer', 'Summer'), ('Whole Year', 'Whole Year')], max_length=15)),
                ('cropname', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soiltype', models.CharField(choices=[('loamy', 'loamy'), ('sandy', 'sandy'), ('clay', 'clay'), ('chalky', 'chalky'), ('peaty', 'peaty'), ('silty', 'silty')], max_length=15)),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('production', models.IntegerField()),
                ('yeild', models.IntegerField()),
            ],
        ),
    ]
