# Generated by Django 4.0.6 on 2022-09-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cropprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropprediction',
            name='yeild',
        ),
    ]
