# Generated by Django 4.0.6 on 2022-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cropprediction_statename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropprediction',
            name='statename',
            field=models.CharField(max_length=15),
        ),
    ]
