# Generated by Django 4.0.6 on 2022-09-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cropprediction_statename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropprediction',
            old_name='cropname',
            new_name='crop',
        ),
        migrations.RenameField(
            model_name='cropprediction',
            old_name='districtname',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='cropprediction',
            old_name='statename',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='cropprediction',
            old_name='cropyear',
            new_name='year',
        ),
    ]
